version: '3.8'

services:
  gaokao-countdown:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: gaokao-countdown-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      # 可选：如果需要持久化数据，可以挂载卷
      - ./data:/app/data:ro
    restart: unless-stopped
    networks:
      - gaokao-network
    # 健康检查
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：如果需要 Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: gaokao-countdown-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # 如果使用 SSL 证书
    depends_on:
      gaokao-countdown:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - gaokao-network
    profiles:
      - nginx  # 使用 profile 使 nginx 可选

networks:
  gaokao-network:
    driver: bridge

# 可选：如果需要数据持久化
volumes:
  app_data:
    driver: local
